/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ndaru Aji
 */
public class Cathering extends javax.swing.JFrame {

    private DefaultTableModel tabel;
    Connection conn;
    Statement stm;
    ResultSet rss;
    /**
     * Creates new form Cathering
     */
    public Cathering() {
        initComponents();
        aktif();
        kosong();
        tabelcath();
    }
    
    protected void aktif(){
        tkode.setEnabled(true);
        tnama.setEnabled(true);
        cariawal.requestFocus();
        
    }
    protected void kosong(){
        tkode.setText("");
        tnama.setText("");
        bpaket.clearSelection();
        harga.setText("");
        cariawal.setText("");
        tcari.setText("");
        teks.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bpaket = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cariawal = new javax.swing.JTextField();
        cek = new javax.swing.JButton();
        tkode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        p1 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        teks = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCathering = new javax.swing.JTable();
        savev = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresht = new javax.swing.JButton();
        close = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        nul = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catering - OMAHPRO WEDDING ORGANIZER");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 8));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_couple_64px.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_couple_64px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel3.setText("OMAHPRO");

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel5.setText("WEDDING");

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("ORGANIZER");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 255, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cari Klien");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kode Klien");

        cariawal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cek.setBackground(new java.awt.Color(153, 255, 204));
        cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_search_more_24px_2.png"))); // NOI18N
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        tkode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nama Klien");

        tnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Pilihan Paket");

        p1.setBackground(new java.awt.Color(153, 255, 204));
        bpaket.add(p1);
        p1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p1.setText("Paket 1");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p2.setBackground(new java.awt.Color(153, 255, 204));
        bpaket.add(p2);
        p2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p2.setText("Paket 2");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.setBackground(new java.awt.Color(153, 255, 204));
        bpaket.add(p3);
        p3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p3.setText("Paket 3");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Harga");

        harga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        teks.setColumns(20);
        teks.setRows(5);
        jScrollPane1.setViewportView(teks);

        tableCathering.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCathering.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCatheringMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCathering);

        savev.setBackground(new java.awt.Color(153, 255, 204));
        savev.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        savev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_sort_by_creation_date_24px.png"))); // NOI18N
        savev.setText("SAVE");
        savev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savevActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(153, 255, 204));
        edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_update_24px.png"))); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(153, 255, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_trash_24px.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        refresht.setBackground(new java.awt.Color(153, 255, 204));
        refresht.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresht.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_refresh_24px.png"))); // NOI18N
        refresht.setText("REFRESH");
        refresht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshtActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(153, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_close_window_24px.png"))); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        tcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cari.setBackground(new java.awt.Color(153, 255, 204));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_search_more_24px_2.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        nul.setBackground(new java.awt.Color(153, 255, 204));
        bpaket.add(nul);
        nul.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nul.setText("-");
        nul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tnama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cariawal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nul)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(close)
                        .addGap(18, 18, 18)
                        .addComponent(refresht)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savev)
                                .addGap(18, 18, 18)
                                .addComponent(edit)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(186, 186, 186))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cariawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1)
                            .addComponent(p2)
                            .addComponent(p3)
                            .addComponent(nul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savev)
                            .addComponent(edit)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close)
                            .addComponent(refresht))
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        try {
            setKoneksi();
            String sql="Select * from tb_konsumen where dbkodeksm like '%" + cariawal.getText() + "%'" +"or dbnamaksm like '%" + cariawal.getText()+"%'";
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kode=rs.getString("dbkodeksm");
                String nama=rs.getString("dbnamaksm");
                tkode.setText(kode);
                tnama.setText(nama);
            }

        } catch (Exception e) {
        }
        tabelcath();
    }//GEN-LAST:event_cekActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
        teks.setText("(65000/pax)*250" +
"1. Nasi Putih\n" +
"2. Nasi Goreng Spesial IKO\n" +
"3. Olahan Sup (Pilihan)\n" +
"4. Olahan Ayam (Pilihan)\n" +
"5. Kakap Asam Manis / Kakap Saus Acar / Kakap Saus Mayonaise\n" +
"6. Gado Gado / Asinan Betawi (Pilihan)\n" +
"7. Krupuk Udang\n" +
"8. Buah Potong\n" +
"9. Puding\n" +
"10. Snack\n" +
"11. Fruitpunch / Lemon Tea\n" +
"12. Mineral Water");
        harga.setText("16250000");
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
        teks.setText("(75000/pax)*250\n" +
"1. Nasi Putih\n" +
"2. Nasi Goreng Spesial IKO\n" +
"3. Olahan Sup (Pilihan)\n" +
"4. Olahan Ayam (Pilihan)\n" +
"5. Beef Teriyaki / Rendang / Black Papper Beef\n" +
"6. Olahan Kakap (Pilihan)\n" +
"7. Gado2/Asinan/Salad (Pilihan)\n" +
"8. Krupuk Udang\n" +
"9. Buah Potong\n" +
"10. Puding\n" +
"11. Snack\n" +
"12. Fruitpunch / Lemon Tea\n" +
"13. Mineral Water");
        harga.setText("18750000");
    }//GEN-LAST:event_p2ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
        teks.setText("(80000/pax)*250\n" +
"1. Nasi Putih\n" +
"2. Nasi Goreng Spesial IKO\n" +
"3. Olahan Sup (Pilihan)\n" +
"4. Olahan Ayam (Pilihan)\n" +
"5. Dendeng Balado Spesial IKO / Beef Teriyaki / Rendang Spesial IKO / Black Papper Beef\n" +
"6. Olahan Kakap (Pilihan)\n" +
"7. Gado2/Asinan/Salad (Pilihan)\n" +
"8. Makaroni Schotel\n" +
"9. Krupuk Udang\n" +
"10. Buah Potong\n" +
"11. Puding\n" +
"12. Snack\n" +
"13. Fruitpunch\n" +
"14. Lemon Tea\n" +
"15. Mineral Water");
        harga.setText("20000000");
    }//GEN-LAST:event_p3ActionPerformed
        
    private void savevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savevActionPerformed
        // TODO add your handling code here:
        String jenis = null;
         if(p1.isSelected()){
           jenis = "Paket 1";
          }else if(p2.isSelected()){
            jenis = "Paket 2";
          }else if (p3.isSelected()){
            jenis = "Paket 3";
          }else if (nul.isSelected()){
            jenis = "Kosong";
          }
         
         
         String sql = "insert into tb_cathering values (?,?,?,?)";
            try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tkode.getText());
            stat.setString(2, tnama.getText());
            stat.setString(3, jenis);
            stat.setString(4, harga.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            }
            catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
            }
            kosong();
            tabelcath();
            
    }//GEN-LAST:event_savevActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String jenis = null;
         if(p1.isSelected()){
           jenis = "Paket 1";
          }else if(p2.isSelected()){
            jenis = "Paket 2";
          }else if (p3.isSelected()){
            jenis = "Paket 3";
          }else if (nul.isSelected()){
            jenis = "Kosong";
          }
        try{
            String sql = "update tb_cathering set "
                    + "dbkodeksm=?,"
                    + "dbnamaksm=?,"
                    + "dbpaketcath=?,"
                    + "dbhargacath=?"
                    + "where dbkodeksm='"+tkode.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tkode.getText());
            stat.setString(2, tnama.getText());
            stat.setString(3, jenis);
            stat.setString(4, harga.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            cariawal.requestFocus();
            }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
            }
            tabelcath();
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "delete from tb_cathering where dbkodeksm ='"+tkode.getText()+"'";
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                kosong();
                
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
             }
         }
         tabelcath();
         kosong();
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshtActionPerformed
        // TODO add your handling code here:
        aktif();
        kosong();
        tabelcath();
    }//GEN-LAST:event_refreshtActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        Object header[]={"KODE KLIEN","NAMA KLIEN","JENIS","HARGA"};
        DefaultTableModel ok=new DefaultTableModel(null,header);
        tableCathering.setModel(ok);
        setKoneksi();
        
        String sql="Select * from tb_cathering where dbkodeksm like '%" + tcari.getText() + "%'" +"or dbnamaksm like '%" + tcari.getText()+"%'";
       
          try {
            ResultSet rss=stm.executeQuery(sql);
            while (rss.next())
            {
                String a=rss.getString("dbkodeksm");
                String b=rss.getString("dbnamaksm");
                String c=rss.getString("dbpaketcath");
                String d=rss.getString("dbhargacath");
                String kolom[]={a,b,c,d};
                ok.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }//GEN-LAST:event_cariActionPerformed

    private void tableCatheringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCatheringMouseClicked
        // TODO add your handling code here:
        int bar = tableCathering.getSelectedRow();
        
        String a = tableCathering.getValueAt(bar, 0).toString();
        String b = tableCathering.getValueAt(bar, 1).toString();
        String c = tableCathering.getValueAt(bar, 2).toString();
        String d = tableCathering.getValueAt(bar,3).toString();
        
        tkode.setText(a);
        tnama.setText(b);
        if(null == c){
            nul.setSelected(true);
        }else switch (c) {
            case "Paket 1":
                p1.setSelected(true);
                break;
            case "Paket 2":
                p2.setSelected(true);
                break;
            case "Paket 3":
                p3.setSelected(true);
                break;    
            default:
                nul.setSelected(true);
                break;
        }
        harga.setText(d);
    }//GEN-LAST:event_tableCatheringMouseClicked

    private void nulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nulActionPerformed
        // TODO add your handling code here:
        teks.setText("Tidak pilih paket");
        harga.setText("0");
    }//GEN-LAST:event_nulActionPerformed

    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/wo","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }

public void tabelcath(){
        Object header[]={"KODE KLIEN","NAMA KLIEN","JENIS","HARGA"};
        DefaultTableModel ok=new DefaultTableModel(null,header);
        tableCathering.setModel(ok);
        setKoneksi();
        String sql="select*from tb_cathering";
        try {
            ResultSet rss=stm.executeQuery(sql);
            while (rss.next())
            {
                String a=rss.getString("dbkodeksm");
                String b=rss.getString("dbnamaksm");
                String c=rss.getString("dbpaketcath");
                String d=rss.getString("dbhargacath");
                String kolom[]={a,b,c,d};
                ok.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cathering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bpaket;
    private javax.swing.JButton cari;
    private javax.swing.JTextField cariawal;
    private javax.swing.JButton cek;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton nul;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JButton refresht;
    private javax.swing.JButton savev;
    private javax.swing.JTable tableCathering;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextArea teks;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    // End of variables declaration//GEN-END:variables
}
