/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ndaru Aji
 */
public class Reservation extends javax.swing.JFrame {

    private DefaultTableModel tabel;
    Connection conn;
    Statement stm;
    ResultSet rss;
    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
        aktif();
        kosong();
        tabelpesan();
    }

    public static Date getTanggalFromTable (JTable table, int kolom){
        JTable tabele = table;
        String tgl= String.valueOf(table.getValueAt(table.getSelectedRow(),kolom));
        Date tanggal = null;
        try{
            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
            
        }catch(ParseException ex){
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE,null,ex);
        }
        return tanggal;
    }
    
    protected void aktif(){
        tkode.setEnabled(true);
        tnama.setEnabled(true);
        cariawal.requestFocus();
    }
    
    protected void kosong (){
        tkode.setText("");
        tnama.setText("");
        cariawal.setText("");
        paketcath.setText("");
        paketmua.setText("");
        paketdekor.setText("");
        hargacath.setText("");
        hargadekor.setText("");
        hargamua.setText("");
        total.setText("");
        tcari.setText("");
        tglreservasi.setDate(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cariawal = new javax.swing.JTextField();
        cek = new javax.swing.JButton();
        tkode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepesan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tglreservasi = new com.toedter.calendar.JDateChooser();
        save = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paketcath = new javax.swing.JTextField();
        paketmua = new javax.swing.JTextField();
        paketdekor = new javax.swing.JTextField();
        hargacath = new javax.swing.JTextField();
        hargamua = new javax.swing.JTextField();
        hargadekor = new javax.swing.JTextField();
        tcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_sort_by_creation_date_24px.png"))); // NOI18N
        jButton1.setText("SAVE");

        jButton5.setBackground(new java.awt.Color(153, 255, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_close_window_24px.png"))); // NOI18N
        jButton5.setText("EDIT");

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_update_24px.png"))); // NOI18N
        jButton2.setText("EDIT");

        jButton3.setBackground(new java.awt.Color(153, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_trash_24px.png"))); // NOI18N
        jButton3.setText("DELETE");

        jButton4.setBackground(new java.awt.Color(153, 255, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_refresh_24px.png"))); // NOI18N
        jButton4.setText("REFRESH");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PEMESANAN - OMAHPRO WEDDING ORGANIZER");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 8));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_couple_64px.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_couple_64px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel3.setText("OMAHPRO");

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel5.setText("WEDDING");

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("ORGANIZER");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 255, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cari Klien");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Kode Klien");

        cariawal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cek.setBackground(new java.awt.Color(153, 255, 204));
        cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_search_more_24px_2.png"))); // NOI18N
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        tkode.setEditable(false);
        tkode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nama Klien");

        tnama.setEditable(false);
        tnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total Harga Paket");

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tablepesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepesanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablepesan);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Reservasi");

        save.setBackground(new java.awt.Color(153, 255, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_sort_by_creation_date_24px.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_close_window_24px.png"))); // NOI18N
        jButton7.setText("CLOSE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 255, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_update_24px.png"))); // NOI18N
        jButton8.setText("EDIT");

        delete.setBackground(new java.awt.Color(153, 255, 204));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_trash_24px.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 255, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_refresh_24px.png"))); // NOI18N
        jButton10.setText("REFRESH");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Catering");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dekorasi");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Mua");

        paketcath.setEditable(false);
        paketcath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        paketmua.setEditable(false);
        paketmua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        paketdekor.setEditable(false);
        paketdekor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        hargacath.setEditable(false);
        hargacath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        hargamua.setEditable(false);
        hargamua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        hargadekor.setEditable(false);
        hargadekor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cari.setBackground(new java.awt.Color(153, 255, 204));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tampilan/icon/icons8_search_more_24px_2.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8))
                                            .addGap(53, 53, 53)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(cariawal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tglreservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(124, 124, 124)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel10))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(paketdekor, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(paketcath, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                .addComponent(paketmua))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(hargadekor, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(hargacath)
                                                .addComponent(hargamua, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(32, 34, Short.MAX_VALUE))))
            .addComponent(jTextField1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(cariawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(paketcath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(paketmua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(paketdekor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tglreservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(delete)
                            .addComponent(jButton10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hargacath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargamua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargadekor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        try {
            setKoneksi();
            String sql="Select * from tb_konsumen where dbkodeksm like '%" + cariawal.getText() + "%'" +"or dbnamaksm like '%" + cariawal.getText()+"%'";
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String nama=rs.getString("dbnamaksm");
                String kode=rs.getString("dbkodeksm");
                tkode.setText(kode);
                tnama.setText(nama);
                
            }

        } catch (Exception e) {
        } paketcath();
            paketdekor();
            paketmua();
            tanggal();
            
        
        int harga1, harga2, harga3, jumlah;
        
        harga1 = Integer.parseInt(hargacath.getText());
        harga2 = Integer.parseInt(hargamua.getText());
        harga3 = Integer.parseInt(hargadekor.getText());
        
        jumlah = harga1 + harga2 + harga3;
        
        total.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_cekActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String tampilan="yyyy-MM-dd";
         SimpleDateFormat wr= new SimpleDateFormat(tampilan);
         String tanggal = String.valueOf(wr.format(tglreservasi.getDate()));
            String sql = "insert into tb_pesanan values (?,?,?,?,?,?,?)";
            try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tanggal);
            stat.setString(2, tkode.getText());
            stat.setString(3, tnama.getText());
            stat.setString(4, paketcath.getText());
            stat.setString(5, paketdekor.getText());
            stat.setString(6, paketmua.getText());
            stat.setString(7, total.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            }
            catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
            }
            tabelpesan();
            kosong();
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "delete from tb_pesanan where dbkodeksm ='"+tkode.getText()+"'";
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                kosong();
                
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
             }
         }
         tabelpesan();
         kosong();
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        kosong();
        tabelpesan();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tablepesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepesanMouseClicked
        // TODO add your handling code here:
        int bar = tablepesan.getSelectedRow();
        tglreservasi.setDate(getTanggalFromTable(tablepesan, 0));
        String a = tablepesan.getValueAt(bar, 1).toString();
        String b = tablepesan.getValueAt(bar, 2).toString();
        String c = tablepesan.getValueAt(bar, 3).toString();
        String d = tablepesan.getValueAt(bar, 4).toString();
        String e = tablepesan.getValueAt(bar, 5).toString();
        String f = tablepesan.getValueAt(bar, 6).toString();
        
        tkode.setText(a);
        tnama.setText(b);
        paketcath.setText(c);
        paketdekor.setText(d);
        paketmua.setText(e);
        total.setText(f);
    }//GEN-LAST:event_tablepesanMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        Object header[]={"TANGGAL RESERVASI","KODE KLIEN","NAMA KLIEN","CATHERING","DEKORASI","MUA","HARGA RESERVASI"};
        DefaultTableModel ok=new DefaultTableModel(null,header);
        tablepesan.setModel(ok);
        setKoneksi();
        
        String sql="Select * from tb_pesanan where dbkodeksm like '%" + tcari.getText() + "%'" +"or dbnamaksm like '%" + tcari.getText()+"%'";
       
          try {
            ResultSet res=stm.executeQuery(sql);
            while (res.next())
            {
                String a=res.getString("dbtanggal");
                String b=res.getString("dbkodeksm");
                String c=res.getString("dbnamaksm");
                String d=res.getString("dbcath");
                String e=res.getString("dbdekor");
                String f=res.getString("dbmua");
                String g=res.getString("dbjumlah");
                String kolom[]={a,b,c,d,e,f,g};
                ok.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }//GEN-LAST:event_cariActionPerformed

    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/wo","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
    
    public Connection paketcath(){ 
        try {
            setKoneksi();
            String sql="Select * from tb_cathering where dbkodeksm like '%" + cariawal.getText() + "%'" +"or dbnamaksm like '%" + cariawal.getText()+"%'";
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String pkt=rs.getString("dbpaketcath");
                String harga=rs.getString("dbhargacath");
                paketcath.setText(pkt);
                hargacath.setText(harga);
            }

        } catch (Exception e) {
        }
        return conn;
    }
    
    public Connection paketdekor(){ 
        try {
            setKoneksi();
            String sql="Select * from tb_dekorasi where dbkodeksm like '%" + cariawal.getText() + "%'" +"or dbnamaksm like '%" + cariawal.getText()+"%'";
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String pkt=rs.getString("dbpaketdekor");
                String harga=rs.getString("dbhargadekor");
                hargadekor.setText(harga);
                paketdekor.setText(pkt);
            }

        } catch (Exception e) {
        }
        return conn;
    }
    
    public Connection paketmua(){ 
        try {
            setKoneksi();
            String sql="Select * from tb_mua where dbkodeksm like '%" + cariawal.getText() + "%'" +"or dbnamaksm like '%" + cariawal.getText()+"%'";
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String pkt=rs.getString("dbpaketmua");
                String harga=rs.getString("dbhargamua");
                paketmua.setText(pkt);
                hargamua.setText(harga);
            }

        } catch (Exception e) {
        }
        return conn;
    }
    
    public Connection tanggal(){ 
        try {
            setKoneksi();
            String sql="Select * from tb_konsumen where dbkodeksm like '%" + tkode.getText() + "%'" ;
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                tglreservasi.setDate(rs.getDate("dbtanggal"));
            }

        } catch (Exception e) {
        }
        return conn;
    }
    
    public void tabelpesan(){
        Object header[]={"TANGGAL RESERVASI","KODE KLIEN","NAMA KLIEN","CATHERING","DEKORASI","MUA","HARGA RESERVASI"};
        DefaultTableModel ok=new DefaultTableModel(null,header);
        tablepesan.setModel(ok);
        setKoneksi();
        String sql="select*from tb_pesanan";
        try {
            ResultSet res=stm.executeQuery(sql);
            while (res.next())
            {
                String a=res.getString("dbtanggal");
                String b=res.getString("dbkodeksm");
                String c=res.getString("dbnamaksm");
                String d=res.getString("dbcath");
                String e=res.getString("dbdekor");
                String f=res.getString("dbmua");
                String g=res.getString("dbjumlah");
                String kolom[]={a,b,c,d,e,f,g};
                ok.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField cariawal;
    private javax.swing.JButton cek;
    private javax.swing.JButton delete;
    private javax.swing.JTextField hargacath;
    private javax.swing.JTextField hargadekor;
    private javax.swing.JTextField hargamua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField paketcath;
    private javax.swing.JTextField paketdekor;
    private javax.swing.JTextField paketmua;
    private javax.swing.JButton save;
    private javax.swing.JTable tablepesan;
    private javax.swing.JTextField tcari;
    private com.toedter.calendar.JDateChooser tglreservasi;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
